version: '3.8'
services:

  db:
    container_name: Planner_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'spp_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./SQLInitScript.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

  client:
    container_name: Planner_Frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./Frontend:/app
    
  nginx:
    container_name: Planner_nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    
  api:
    container_name: Planner_Backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./Backend:/app

volumes:
  db:
    

    



  